apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      completions: 1
      manualSelector: false
      parallelism: 1
      template:
        spec:
          automountServiceAccountToken: false
          containers:
          - command: [ "/bin/sh", "-c", "nl=$'\n'; cr=$'\r'; nikto.pl -h {{ .Values.test_url }} -useragent \"nikto${cr}${nl}X-Forwarded-For: {{ .Values.source_ip_address }}\"" ]
            image: vgartvichwallarm/nikto:latest
            imagePullPolicy: Always
            name: nikto
          initContainers:
          - command:
            - /bin/sh
            - -c
            - sleep `shuf -i1-{{ .Values.delay }} -n1`m; date; echo Done sleeping
            image: busybox
            imagePullPolicy: Always
            name: random-sleep
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
  schedule: "{{ .Values.schedule }}"
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 10
  suspend: false
