apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      completions: 1
      manualSelector: false
      parallelism: 1
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Release.Name }}-ip-addresses
          automountServiceAccountToken: false
          containers:
          - command: [ "/bin/sh", "-c", "IP=`shuf /tmp/addresses.txt |head -1`; nl=$'\n'; cr=$'\r'; nikto.pl -h {{ .Values.test_url }} -useragent \"nikto${cr}${nl}X-Forwarded-For: $IP\"" ]
            image: vgartvichwallarm/nikto:latest
            imagePullPolicy: IfNotPresent
            name: nikto
            volumeMounts:
            - name: config-volume
              mountPath: /tmp/addresses.txt
              subPath: addresses.txt
#          initContainers:
#          - command:
#            - /bin/sh
#            - -c
#            - sleep `shuf -i1-{{ .Values.delay }} -n1`m; date; echo Done sleeping
#            image: busybox
#            imagePullPolicy: IfNotPresent
#            name: random-sleep
#            resources: {}
#            terminationMessagePath: /dev/termination-log
#            terminationMessagePolicy: File
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
  schedule: "{{ .Values.schedule }}"
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 10
  suspend: false
