apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}.secret
type: Opaque
data:
  wallarm_uuid: {{ .Values.wallarm_uuid | b64enc }}
  wallarm_secret: {{ .Values.wallarm_secret | b64enc }}
  collector_address: {{ .Values.collector_address | b64enc }}
