apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-zipbomb
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      completions: 1
      manualSelector: false
      parallelism: 1
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Release.Name }}-ip-addresses
          automountServiceAccountToken: false
          containers:
          - command: [ "/bin/sh", "-c", "IP=`shuf /tmp/addresses.txt |head -1`; curl -v --data-binary @zblg.zip https://echo-server.{{ .Values.domain_name }}/ -H X-Forwarded-For:$IP" ]
            image: vgartvichwallarm/ubuntu18:latest
            imagePullPolicy: IfNotPresent
            name: zipbomb
            volumeMounts:
            - name: config-volume
              mountPath: /tmp/addresses.txt
              subPath: addresses.txt
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
  schedule: "{{ .Values.schedule_zipbomb }}"
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 10
  suspend: false
