apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      completions: 1
      manualSelector: false
      parallelism: 1
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Release.Name }}-ip-addresses
            - name: config-scripts
              configMap:
                name: {{ .Release.Name }}-scripts
          automountServiceAccountToken: false
          containers:
          - command: [ "/bin/sh", "-c", "apt-get update -y; apt-get install curl -y; IP=`shuf /tmp/addresses.txt |head -1`; sh /tmp/send-tiredfulapi-attacks.sh tiredful-api.{{ .Values.domain_name }} $IP" ]
            image: ubuntu:18.04
            imagePullPolicy: IfNotPresent
            name: scripts-tiredful-api
            volumeMounts:
            - name: config-volume
              mountPath: /tmp/addresses.txt
              subPath: addresses.txt
            - name: config-scripts
              mountPath: /tmp/send-tiredfulapi-attacks.sh
              subPath: send-tiredfulapi-attacks.sh
          - command: [ "/bin/sh", "-c", "apt-get update -y; apt-get install curl -y; IP=`shuf /tmp/addresses.txt |head -1`; sh /tmp/send-dvwa-attacks.sh -d dvwa.{{ .Values.domain_name }} -i $IP" ]
            image: ubuntu:18.04
            imagePullPolicy: IfNotPresent
            name: scripts-dvwa
            volumeMounts:
            - name: config-volume
              mountPath: /tmp/addresses.txt
              subPath: addresses.txt
            - name: config-scripts
              mountPath: /tmp/send-dvwa-attacks.sh
              subPath: send-dvwa-attacks.sh
#          initContainers:
#          - command:
#            - /bin/sh
#            - -c
#            - sleep `shuf -i1-{{ .Values.delay }} -n1`m; date; echo Done sleeping
#            image: busybox
#            imagePullPolicy: IfNotPresent
#            name: random-sleep
#            resources: {}
#            terminationMessagePath: /dev/termination-log
#            terminationMessagePolicy: File
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
  schedule: "{{ .Values.schedule }}"
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 10
  suspend: false
